{% set name = "hdxms-datasets" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hdxms_datasets-{{ version }}.tar.gz
  sha256: b3cc3b44b80e117e90c5cc368e273198fcc730b72fb59233dbff387fb460467d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - pandas
    - pyyaml
    - requests
    - packaging

test:
  imports:
    - hdxms_datasets
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Download and parse curated HDX-MS datasets
  home: https://github.com/Jhsmit/hdxms-datasets/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Jhsmit
