{% set name = "hdxms-datasets" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hdxms_datasets-{{ version }}.tar.gz
  sha256: 515a840e83b094e83af35afc173a0efacf6aa64e3539e1cb1e8642b61b8d8705

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.9,<4.0
    - pyyaml >=6.0,<7.0
    - omegaconf >=2.3.0,<3.0.0
    - packaging >=22.0,<23.0
    - pandas >=1.5.2,<2.0.0
    - requests >=2.28.1,<3.0.0

test:
  imports:
    - hdxms_datasets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Jhsmit/hdxms-datasets/
  summary: Download and parse curated HDX-MS datasets
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Jhsmit
